version: '3.5'

services:
  postgres:
    container_name: postgres-test
    image: postgres:14.5
    restart: always
    ports:
      - 11432:5432
    networks:
      - database
    volumes:
      - postgres-test:/var/lib/postgresql/data
      - ./conf/create-user-and-db.sh:/docker-entrypoint-initdb.d/create-user-and-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'Europe/Rome'
      PGTZ: 'Europe/Rome'

networks:
  database:
    name: database

volumes:
  postgres-test:
    name: postgres-test
